-- SQL Server schema for SpaceBookingApp (Basketball Court)

CREATE TABLE Users (
  UserId INT IDENTITY(1,1) PRIMARY KEY,
  FullName NVARCHAR(200) NOT NULL,
  Email NVARCHAR(320) NULL,
  Phone NVARCHAR(32) NULL,
  Role NVARCHAR(20) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE UNIQUE INDEX UX_Users_Phone
  ON Users(Phone)
  WHERE Phone IS NOT NULL;

CREATE TABLE AuthProviders (
  ProviderId INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  ProviderType NVARCHAR(20) NOT NULL,
  ProviderSubject NVARCHAR(200) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_AuthProviders_UserId FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE UNIQUE INDEX UX_AuthProviders_Provider
  ON AuthProviders(ProviderType, ProviderSubject);

CREATE TABLE Bookings (
  BookingId INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  StartAt DATETIME2 NOT NULL,
  EndAt DATETIME2 NOT NULL,
  DurationHours INT NOT NULL,
  Status NVARCHAR(40) NOT NULL,
  HoldExpiresAt DATETIME2 NULL,
  NeedsApproval BIT NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Bookings_UserId FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE BookingSlots (
  BookingSlotId INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT NOT NULL,
  SlotStartAt DATETIME2 NOT NULL,
  SlotStatus NVARCHAR(40) NOT NULL,
  CONSTRAINT FK_BookingSlots_BookingId FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId)
);

CREATE UNIQUE INDEX UX_BookingSlots_SlotStartAt_Active
  ON BookingSlots(SlotStartAt)
  WHERE SlotStatus IN (
    'HELD',
    'PENDING_PAYMENT',
    'PENDING_APPROVAL',
    'APPROVED_AWAITING_PAYMENT',
    'CONFIRMED'
  );

CREATE UNIQUE INDEX UX_Bookings_User_Active
  ON Bookings(UserId)
  WHERE Status IN (
    'HELD',
    'PENDING_PAYMENT',
    'PENDING_APPROVAL',
    'APPROVED_AWAITING_PAYMENT',
    'CONFIRMED'
  );

CREATE TABLE Blocks (
  BlockId INT IDENTITY(1,1) PRIMARY KEY,
  StartAt DATETIME2 NOT NULL,
  EndAt DATETIME2 NOT NULL,
  Reason NVARCHAR(500) NULL,
  CreatedByAdminId INT NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Blocks_AdminId FOREIGN KEY (CreatedByAdminId) REFERENCES Users(UserId)
);

CREATE INDEX IX_Blocks_StartAt_EndAt ON Blocks(StartAt, EndAt);

CREATE TABLE Payments (
  PaymentId INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT NOT NULL,
  Provider NVARCHAR(20) NOT NULL,
  CheckoutSessionId NVARCHAR(200) NULL,
  PaymentStatus NVARCHAR(40) NOT NULL,
  Amount INT NOT NULL,
  Currency NVARCHAR(10) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Payments_BookingId FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId)
);

CREATE TABLE Refunds (
  RefundId INT IDENTITY(1,1) PRIMARY KEY,
  PaymentId INT NOT NULL,
  Provider NVARCHAR(20) NOT NULL,
  ProviderRefundId NVARCHAR(200) NULL,
  Amount INT NOT NULL,
  Currency NVARCHAR(10) NOT NULL,
  Status NVARCHAR(40) NOT NULL,
  Reason NVARCHAR(200) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Refunds_PaymentId FOREIGN KEY (PaymentId) REFERENCES Payments(PaymentId)
);

CREATE TABLE WebhookEvents (
  EventId NVARCHAR(200) PRIMARY KEY,
  Provider NVARCHAR(20) NOT NULL,
  ReceivedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  RawJson NVARCHAR(MAX) NOT NULL,
  ProcessedAt DATETIME2 NULL,
  ProcessingStatus NVARCHAR(40) NOT NULL
);

CREATE TABLE BookingEdits (
  EditId INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT NOT NULL,
  ActorUserId INT NOT NULL,
  ActorRole NVARCHAR(20) NOT NULL,
  EditedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Reason NVARCHAR(500) NULL,
  OldStartAt DATETIME2 NOT NULL,
  OldEndAt DATETIME2 NOT NULL,
  NewStartAt DATETIME2 NOT NULL,
  NewEndAt DATETIME2 NOT NULL,
  OldStatus NVARCHAR(40) NOT NULL,
  NewStatus NVARCHAR(40) NOT NULL,
  PriceDelta INT NULL,
  RequiresApproval BIT NOT NULL,
  CONSTRAINT FK_BookingEdits_BookingId FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId),
  CONSTRAINT FK_BookingEdits_ActorUserId FOREIGN KEY (ActorUserId) REFERENCES Users(UserId)
);

CREATE TABLE BookingChangeRequests (
  ChangeRequestId INT IDENTITY(1,1) PRIMARY KEY,
  BookingId INT NOT NULL,
  RequestedByUserId INT NOT NULL,
  OldStartAt DATETIME2 NOT NULL,
  OldEndAt DATETIME2 NOT NULL,
  OldDuration INT NOT NULL,
  NewStartAt DATETIME2 NOT NULL,
  NewEndAt DATETIME2 NOT NULL,
  NewDuration INT NOT NULL,
  PriceDelta INT NOT NULL,
  Status NVARCHAR(40) NOT NULL,
  HoldExpiresAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_BookingChangeRequests_BookingId FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId),
  CONSTRAINT FK_BookingChangeRequests_UserId FOREIGN KEY (RequestedByUserId) REFERENCES Users(UserId)
);
